--Criando tabela
CREATE TABLE TALUNO
 (
    COD_ALUNO INTEGER NOT NULL,
    NOME VARCHAR(30),
    CIDADE VARCHAR(30),
    CEP VARCHAR(10),
    PRIMARY KEY (COD_ALUNO)
 );
 --Selecionando tabela
 SELECT * FROM TALUNO
--Criando sequencia 
 CREATE SEQUENCE SEQ_ALUNO START WITH 4;
--Inserindo valores com sequência
INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES(SEQ_ALUNO.NEXTVAL, 'ACHOEIRINHA','36986523');

CREATE TABLE TCURSO 
 (
    COD_CURSO INTEGER NOT NULL,
    NOME VARCHAR(30),
    VALOR NUMBER(8,2),
    CARGA_HORARIA INTEGER
 ); 

SELECT * FROM TCURSO

INSERT INTO TCURSO VALUES(4,'POWER BI','350','80');

COMMIT,

CREATE TABLE TCONTRATO
 (
    COD_CONTRATO INTEGER NOT NULL,
    DATA DATE,
    COD_ALUNO INTEGER,
    TOTAL NUMBER (8,2),
    DESCONTO NUMBER (5,2)
 ); 

INSERT INTO TCONTRATO VALUES(5, SYSDATE-5 ,2,360,10);


--Criando view
CREATE OR REPLACE VIEW V_ALUNO
AS
  SELECT COD_ALUNO AS CODIGO, ESTADO,
         NOME AS ALUNO, CIDADE
  FROM   TALUNO
  WHERE  ESTADO = 'RS';

SELECT * FROM TALUNO

--Inserir coluna na tabela
ALTER TABLE TALUNO ADD ESTADO VARCHAR(30);
--Alterando valores em colunas null
UPDATE TALUNO SET
   ESTADO = 'RS'
WHERE COD_ALUNO = 5;   

--Nome e conteudo das views
SELECT VIEW_NAME, TEXT
FROM USER_VIEWS;

--View com parametros de saida
CREATE OR REPLACE VIEW V_ALUNO2(COD, ALUNO, CIDADE)
AS
  SELECT COD_ALUNO, NOME, CIDADE
  FROM TALUNO;
  
SELECT * FROM V_ALUNO2;  
  
--View complexa
CREATE OR REPLACE VIEW V_CONTRATO
AS
  SELECT TRUNC(DATA) AS DATA,
  MAX(DESCONTO) MAXIMO,
  AVG(DESCONTO) MEDIA,
  COUNT(*) QTDE
FROM TCONTRATO
GROUP BY TRUNC(DATA);
--Select view
SELECT * FROM V_CONTRATO

--Criando sequencias
CREATE SEQUENCE SEQ_ALUNO1
START WITH 60 --Valor inicial
INCREMENT BY 2 --Quantidade a incrementar
MINVALUE 60    --Valor minimo
MAXVALUE 100  --Valor maximo
NOCACHE --Não guarda em cache faixa de valores --20
NOCYCLE;
--Inserir registros atraves da sequencia criada
INSERT INTO TALUNO (COD_ALUNO,NOME)
VALUES (SEQ_ALUNO1.NEXTVAL,'MASTER TRAINING');

--Select sequencias criadas
SELECT * FROM USER_SEQUENCES;

--Apagar sequencia
DROP SEQUENCE SEQ_ALUNO1

--Indices secundarios
CREATE INDEX IND_TALUNO_NOME ON TALUNO(NOME);
--Selecionando atraves do indice criado
SELECT NOME FROM TALUNO
WHERE NOME LIKE '%MA%';
--select indices driados
SELECT * FROM USER_INDEXES;
--Excluir index
DROP INDEX IND_TALUNO_NOME

--Sinonimos(apelidar tabela)
CREATE SYNONYM ALU FOR TALUNO;





