CREATE TABLE TALUNO
 (
    COD_ALUNO INTEGER NOT NULL,
    NOME VARCHAR(30),
    CIDADE VARCHAR(30),
    CEP VARCHAR(10),
    PRIMARY KEY (COD_ALUNO)
 );
 
 SELECT * FROM TALUNO
 CREATE SEQUENCE SEQ_ALUNO START WITH 4;

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES(SEQ_ALUNO.NEXTVAL, 'ACHOEIRINHA','36986523');

CREATE TABLE TCURSO 
 (
    COD_CURSO INTEGER NOT NULL,
    NOME VARCHAR(30),
    VALOR NUMBER(8,2),
    CARGA_HORARIA INTEGER
 ); 

SELECT * FROM TCURSO

INSERT INTO TCURSO VALUES(4,'POWER BI','350','80');

COMMIT,

CREATE TABLE TCONTRATO
 (
    COD_CONTRATO INTEGER NOT NULL,
    DATA DATE,
    COD_ALUNO INTEGER,
    TOTAL NUMBER (8,2),
    DESCONTO NUMBER (5,2)
 ); 

INSERT INTO TCONTRATO VALUES(5, SYSDATE-5 ,2,360,10);


